/**
 * Seed data for the 17 UN Sustainable Development Goals and their official
 * targets. This is the same reference content that powers the "Goals and
 * targets" accordion page on the live site — static, rarely-changing UN text,
 * so it's seeded once here rather than entered by hand in the admin UI.
 *
 * Colors are the official SDG brand colors (un.org/sustainabledevelopment
 * brand guidelines). goal-02/03/04 were cross-checked against the live
 * site's own CSS custom properties and match exactly.
 */

export type SeedGoal = {
  number: number
  code: string
  title: string
  colorHex: string
}

export type SeedTarget = {
  code: string
  goalNumber: number
  title: string
  description: string
}

export const sdgGoals: SeedGoal[] = [
  { number: 1, code: 'goal-01', title: 'No Poverty', colorHex: '#E5243B' },
  { number: 2, code: 'goal-02', title: 'No Hunger', colorHex: '#DDA63A' },
  { number: 3, code: 'goal-03', title: 'Good Health and Well-being', colorHex: '#4C9F38' },
  { number: 4, code: 'goal-04', title: 'Quality Education', colorHex: '#C5192D' },
  { number: 5, code: 'goal-05', title: 'Gender Equality', colorHex: '#FF3A21' },
  { number: 6, code: 'goal-06', title: 'Clean Water and Sanitation', colorHex: '#26BDE2' },
  { number: 7, code: 'goal-07', title: 'Affordable and Clean Energy', colorHex: '#FCC30B' },
  { number: 8, code: 'goal-08', title: 'Decent Work and Economic Growth', colorHex: '#A21942' },
  {
    number: 9,
    code: 'goal-09',
    title: 'Industry, Innovation and Infrastructure',
    colorHex: '#FD6925',
  },
  { number: 10, code: 'goal-10', title: 'Reduced Inequalities', colorHex: '#DD1367' },
  {
    number: 11,
    code: 'goal-11',
    title: 'Sustainable Cities and Communities',
    colorHex: '#FD9D24',
  },
  {
    number: 12,
    code: 'goal-12',
    title: 'Responsible Consumption and Production',
    colorHex: '#BF8B2E',
  },
  { number: 13, code: 'goal-13', title: 'Climate Action', colorHex: '#3F7E44' },
  { number: 14, code: 'goal-14', title: 'Life Below Water', colorHex: '#0A97D9' },
  { number: 15, code: 'goal-15', title: 'Life On Land', colorHex: '#56C02B' },
  {
    number: 16,
    code: 'goal-16',
    title: 'Peace, Justice and Strong Institutions',
    colorHex: '#00689D',
  },
  { number: 17, code: 'goal-17', title: 'Partnerships for the Goals', colorHex: '#19486A' },
]

export const sdgTargets: SeedTarget[] = [
  // Goal 1: No Poverty
  { code: '1.1', goalNumber: 1, title: 'Eradicate Extreme Poverty', description: 'By 2030, eradicate extreme poverty for all people everywhere, currently measured as people living on less than $1.25 a day.' },
  { code: '1.2', goalNumber: 1, title: 'Reduce Poverty by at least 50%', description: 'By 2030, reduce at least by half the proportion of men, women and children of all ages living in poverty in all its dimensions according to national definitions.' },
  { code: '1.3', goalNumber: 1, title: 'Implement social protection systems', description: 'Implement nationally appropriate social protection systems and measures for all, including floors, and by 2030 achieve substantial coverage of the poor and the vulnerable.' },
  { code: '1.4', goalNumber: 1, title: 'Equal rights to ownership, basic services, technology and economic resources', description: 'By 2030, ensure that all men and women, in particular the poor and the vulnerable, have equal rights to economic resources, as well as access to basic services, ownership and control over land and other forms of property, inheritance, natural resources, appropriate new technology and financial services, including microfinance.' },
  { code: '1.5', goalNumber: 1, title: 'Build resilience to environmental, economic and social disasters', description: 'By 2030, build the resilience of the poor and those in vulnerable situations and reduce their exposure and vulnerability to climate-related extreme events and other economic, social and environmental shocks and disasters.' },
  { code: '1.A', goalNumber: 1, title: 'Mobilize resoucres to implement policies to end poverty', description: 'Ensure significant mobilization of resources from a variety of sources, including through enhanced development cooperation, in order to provide adequate and predictable means for developing countries, in particular least developed countries, to implement programmes and policies to end poverty in all its dimensions.' },
  { code: '1.B', goalNumber: 1, title: 'Create pro-poor and gender-sensitive policy frameworks', description: 'Create sound policy frameworks at the national, regional and international levels, based on pro-poor and gender-sensitive development strategies, to support accelerated investment in poverty eradication actions.' },

  // Goal 2: No Hunger
  { code: '2.1', goalNumber: 2, title: 'Universal access to safe and nutritious food', description: 'By 2030, end hunger and ensure access by all people, in particular the poor and people in vulnerable situations, including infants, to safe, nutritious and sufficient food all year round.' },
  { code: '2.2', goalNumber: 2, title: 'End all forms of malnutrition', description: 'By 2030, end all forms of malnutrition, including achieving, by 2025, the internationally agreed targets on stunting and wasting in children under 5 years of age, and address the nutritional needs of adolescent girls, pregnant and lactating women and older persons.' },
  { code: '2.3', goalNumber: 2, title: 'Double the productivity and incomes of small-scale food producers', description: 'By 2030, double the agricultural productivity and incomes of small-scale food producers, in particular women, indigenous peoples, family farmers, pastoralists and fishers, including through secure and equal access to land, other productive resources and inputs, knowledge, financial services, markets and opportunities for value addition and non-farm employment.' },
  { code: '2.4', goalNumber: 2, title: 'Sustainable food production and resilient agricultural practices', description: 'By 2030, ensure sustainable food production systems and implement resilient agricultural practices that increase productivity and production, that help maintain ecosystems, that strengthen capacity for adaptation to climate change, extreme weather, drought, flooding and other disasters and that progressively improve land and soil quality.' },
  { code: '2.5', goalNumber: 2, title: 'Maintain the genetic diversity in food production', description: 'By 2020, maintain the genetic diversity of seeds, cultivated plants and farmed and domesticated animals and their related wild species, including through soundly managed and diversified seed and plant banks at the national, regional and international levels, and promote access to and fair and equitable sharing of benefits arising from the utilization of genetic resources and associated traditional knowledge, as internationally agreed.' },
  { code: '2.A', goalNumber: 2, title: 'Invest in rural infrastructure, agricultural research, technology and gene banks', description: 'Increase investment, including through enhanced international cooperation, in rural infrastructure, agricultural research and extension services, technology development and plant and livestock gene banks in order to enhance agricultural productive capacity in developing countries, in particular least developed countries.' },
  { code: '2.B', goalNumber: 2, title: 'Prevent agricultural trade restrictions, market distortions and export subsidies', description: 'Correct and prevent trade restrictions and distortions in world agricultural markets, including through the parallel elimination of all forms of agricultural export subsidies and all export measures with equivalent effect, in accordance with the mandate of the Doha Development Round.' },
  { code: '2.C', goalNumber: 2, title: 'Ensure stable food commodity markets and timely access to infomation', description: 'Adopt measures to ensure the proper functioning of food commodity markets and their derivatives and facilitate timely access to market information, including on food reserves, in order to help limit extreme food price volatility.' },

  // Goal 3: Good Health and Well-being
  { code: '3.1', goalNumber: 3, title: 'Reduce maternal mortality', description: 'By 2030, reduce the global maternal mortality ratio to less than 70 per 100,000 live births.' },
  { code: '3.2', goalNumber: 3, title: 'End all preventable deaths under 5 years of age', description: 'By 2030, end preventable deaths of newborns and children under 5 years of age, with all countries aiming to reduce neonatal mortality to at least as low as 12 per 1,000 live births and under-5 mortality to at least as low as 25 per 1,000 live births.' },
  { code: '3.3', goalNumber: 3, title: 'Fight communicable diseases', description: 'By 2030, end the epidemics of AIDS, tuberculosis, malaria and neglected tropical diseases and combat hepatitis, water-borne diseases and other communicable diseases.' },
  { code: '3.4', goalNumber: 3, title: 'Reduce mortality from non-communicable diseases and promote mental health', description: 'By 2030, reduce by one third premature mortality from non-communicable diseases through prevention and treatment and promote mental health and well-being.' },
  { code: '3.5', goalNumber: 3, title: 'Prevent and treat substance abuse', description: 'Strengthen the prevention and treatment of substance abuse, including narcotic drug abuse and harmful use of alcohol.' },
  { code: '3.6', goalNumber: 3, title: 'Reduce road injuries and deaths', description: 'By 2030, halve the number of global deaths and injuries from road traffic accidents.' },
  { code: '3.7', goalNumber: 3, title: 'Universial access to sexual and reproductive care, family planning and education', description: 'By 2030, ensure universal access to sexual and reproductive health-care services, including for family planning, information and education, and the integration of reproductive health into national strategies and programmes.' },
  { code: '3.8', goalNumber: 3, title: 'Achieve universal health coverage', description: 'Achieve universal health coverage, including financial risk protection, access to quality essential health-care services and access to safe, effective, quality and affordable essential medicines and vaccines for all.' },
  { code: '3.9', goalNumber: 3, title: 'Reduce illnesses and death from hazardous chemicals and pollution', description: 'By 2030, substantially reduce the number of deaths and illnesses from hazardous chemicals and air, water and soil pollution and contamination.' },
  { code: '3.A', goalNumber: 3, title: 'Implement the WHO framework convention on tobacco control', description: 'Strengthen the implementation of the World Health Organization Framework Convention on Tobacco Control in all countries, as appropriate.' },
  { code: '3.B', goalNumber: 3, title: 'Support research, development and universal access to affordable vaccines and medicines', description: 'Support the research and development of vaccines and medicines for the communicable and non-communicable diseases that primarily affect developing countries, provide access to affordable essential medicines and vaccines, in accordance with the Doha Declaration on the TRIPS Agreement and Public Health, which affirms the right of developing countries to use to the full the provisions in the Agreement on Trade-Related Aspects of Intellectual Property Rights regarding flexibilities to protect public health, and, in particular, provide access to medicines for all.' },
  { code: '3.C', goalNumber: 3, title: 'Increase health financing and support health workforce in developing countries', description: 'Substantially increase health financing and the recruitment, development, training and retention of the health workforce in developing countries, especially in least developed countries and small island developing States.' },
  { code: '3.D', goalNumber: 3, title: 'Improve early warning systems for global health risks', description: 'Strengthen the capacity of all countries, in particular developing countries, for early warning, risk reduction and management of national and global health risks.' },

  // Goal 4: Quality Education
  { code: '4.1', goalNumber: 4, title: 'Free primary and secondary education', description: 'By 2030, ensure that all girls and boys complete free, equitable and quality primary and secondary education leading to relevant and effective learning outcomes.' },
  { code: '4.2', goalNumber: 4, title: 'Equal access to quality pre-primary education', description: 'By 2030, ensure that all girls and boys have access to quality early childhood development, care and pre-primary education so that they are ready for primary education.' },
  { code: '4.3', goalNumber: 4, title: 'Equal access to affordable technical, vocational and higher education', description: 'By 2030, ensure equal access for all women and men to affordable and quality technical, vocational and tertiary education, including university.' },
  { code: '4.4', goalNumber: 4, title: 'Increase the number of people with relevent skills for financial success', description: 'By 2030, substantially increase the number of youth and adults who have relevant skills, including technical and vocational skills, for employment, decent jobs and entrepreneurship.' },
  { code: '4.5', goalNumber: 4, title: 'Eliminate all discrimination in education', description: 'By 2030, eliminate gender disparities in education and ensure equal access to all levels of education and vocational training for the vulnerable, including persons with disabilities, indigenous peoples and children in vulnerable situations.' },
  { code: '4.6', goalNumber: 4, title: 'Universal literacy and numeracy', description: 'By 2030, ensure that all youth and a substantial proportion of adults, both men and women, achieve literacy and numeracy.' },
  { code: '4.7', goalNumber: 4, title: 'Education for sustainable development and global citizenship', description: "By 2030, ensure that all learners acquire the knowledge and skills needed to promote sustainable development, including, among others, through education for sustainable development and sustainable lifestyles, human rights, gender equality, promotion of a culture of peace and non-violence, global citizenship and appreciation of cultural diversity and of culture's contribution to sustainable development." },
  { code: '4.A', goalNumber: 4, title: 'Build and upgrade inclusive and safe schools', description: 'Build and upgrade education facilities that are child, disability and gender sensitive and provide safe, non-violent, inclusive and effective learning environments for all.' },
  { code: '4.B', goalNumber: 4, title: 'Expand higher education scholarships for developing countries', description: 'By 2020, substantially expand globally the number of scholarships available to developing countries, in particular least developed countries, small island developing States and African countries, for enrolment in higher education, including vocational training and information and communications technology, technical, engineering and scientific programmes, in developed countries and other developing countries.' },
  { code: '4.C', goalNumber: 4, title: 'Increase the supply of qualified teachers in developing countries', description: 'By 2030, substantially increase the supply of qualified teachers, including through international cooperation for teacher training in developing countries, especially least developed countries and small island developing States.' },

  // Goal 5: Gender Equality
  { code: '5.1', goalNumber: 5, title: 'End discrimination against women and girls', description: 'End all forms of discrimination against all women and girls everywhere.' },
  { code: '5.2', goalNumber: 5, title: 'End all violence against and exploitation of women and girls', description: 'Eliminate all forms of violence against all women and girls in the public and private spheres, including trafficking and sexual and other types of exploitation.' },
  { code: '5.3', goalNumber: 5, title: 'Eliminate forced marriages and genital mutilation', description: 'Eliminate all harmful practices, such as child, early and forced marriage and female genital mutilation.' },
  { code: '5.4', goalNumber: 5, title: 'Value unpaid care and promote shared domestic responsibilities', description: 'Recognize and value unpaid care and domestic work through the provision of public services, infrastructure and social protection policies and the promotion of shared responsibility within the household and the family as nationally appropriate.' },
  { code: '5.5', goalNumber: 5, title: 'Ensure full participation in leadership and decision-making', description: "Ensure women's full and effective participation and equal opportunities for leadership at all levels of decision-making in political, economic and public life." },
  { code: '5.6', goalNumber: 5, title: 'Universal access to reproductive health and rights', description: 'Ensure universal access to sexual and reproductive health and reproductive rights as agreed in accordance with the Programme of Action of the International Conference on Population and Development and the Beijing Platform for Action and the outcome documents of their review conferences.' },
  { code: '5.A', goalNumber: 5, title: 'Equal rights to economic resources, property ownership and financial services', description: 'Undertake reforms to give women equal rights to economic resources, as well as access to ownership and control over land and other forms of property, financial services, inheritance and natural resources, in accordance with national laws.' },
  { code: '5.B', goalNumber: 5, title: 'Promote empowerment of women through technology', description: 'Enhance the use of enabling technology, in particular information and communications technology, to promote the empowerment of women.' },
  { code: '5.C', goalNumber: 5, title: 'Adopt and strengthen policies and enforcable legislation for gender equality', description: 'Adopt and strengthen sound policies and enforceable legislation for the promotion of gender equality and the empowerment of all women and girls at all levels.' },

  // Goal 6: Clean Water and Sanitation
  { code: '6.1', goalNumber: 6, title: 'Safe and affordable drinking water', description: 'By 2030, achieve universal and equitable access to safe and affordable drinking water for all.' },
  { code: '6.2', goalNumber: 6, title: 'End open defecation and provide access to sanitation and hygiene', description: 'By 2030, achieve access to adequate and equitable sanitation and hygiene for all and end open defecation, paying special attention to the needs of women and girls and those in vulnerable situations.' },
  { code: '6.3', goalNumber: 6, title: 'Improve water quality, wastewater treatment and safe reuse', description: 'By 2030, improve water quality by reducing pollution, eliminating dumping and minimizing release of hazardous chemicals and materials, halving the proportion of untreated wastewater and substantially increasing recycling and safe reuse globally.' },
  { code: '6.4', goalNumber: 6, title: 'Increase water-use efficency and ensure freshwater supplies', description: 'By 2030, substantially increase water-use efficiency across all sectors and ensure sustainable withdrawals and supply of freshwater to address water scarcity and substantially reduce the number of people suffering from water scarcity.' },
  { code: '6.5', goalNumber: 6, title: 'Implement integrated water resources management', description: 'By 2030, implement integrated water resources management at all levels, including through transboundary cooperation as appropriate.' },
  { code: '6.6', goalNumber: 6, title: 'Protect and restore water-related ecosystems', description: 'By 2030, protect and restore water-related ecosystems, including mountains, forests, wetlands, rivers, aquifers and lakes.' },
  { code: '6.A', goalNumber: 6, title: 'Expand water and sanitation support to developing countries', description: 'By 2030, expand international cooperation and capacity-building support to developing countries in water- and sanitation-related activities and programmes, including water harvesting, desalination, water efficiency, wastewater treatment, recycling and reuse technologies.' },
  { code: '6.B', goalNumber: 6, title: 'Support local engagement in water and sanitation management', description: 'Support and strengthen the participation of local communities in improving water and sanitation management.' },

  // Goal 7: Affordable and Clean Energy
  { code: '7.1', goalNumber: 7, title: 'Universal access to modern energy', description: 'By 2030, ensure universal access to affordable, reliable and modern energy services.' },
  { code: '7.2', goalNumber: 7, title: 'Increase global percentage of renewable energy', description: 'By 2030, increase substantially the share of renewable energy in the global energy mix.' },
  { code: '7.3', goalNumber: 7, title: 'Double the improvement in energy efficency', description: 'By 2030, double the global rate of improvement in energy efficiency.' },
  { code: '7.A', goalNumber: 7, title: 'Promote access to research, technology and investments in clean energy', description: 'By 2030, enhance international cooperation to facilitate access to clean energy research and technology, including renewable energy, energy efficiency and advanced and cleaner fossil-fuel technology, and promote investment in energy infrastructure and clean energy technology.' },
  { code: '7.B', goalNumber: 7, title: 'Expand and upgrade energy services for developing countries', description: 'By 2030, expand infrastructure and upgrade technology for supplying modern and sustainable energy services for all in developing countries, in particular least developed countries, small island developing States and landlocked developing countries, in accordance with their respective programmes of support.' },

  // Goal 8: Decent Work and Economic Growth
  { code: '8.1', goalNumber: 8, title: 'Sustainable economic growth', description: 'Sustain per capital economic growth in accordance with national circumstances and, in particular, at least 7 per cent gross domestic product growth per annum in the least developed countries.' },
  { code: '8.2', goalNumber: 8, title: 'Diversify, innovate and upgrade for economic productivity', description: 'Achieve higher levels of economic productivity through diversification, technological upgrading and innovation, including through a focus on high-value added and labour-intensive sectors.' },
  { code: '8.3', goalNumber: 8, title: 'Promote policies to support job creation and growing enterprises', description: 'Promote development-oriented policies that support productive activities, decent job creation, entrepreneurship, creativity and innovation, and encourage the formalization and growth of micro-, small- and medium-sized enterprises, including through access to financial services.' },
  { code: '8.4', goalNumber: 8, title: 'Improve resource efficiency in consumption and production', description: 'Improve progressively, through 2030, global resource efficiency in consumption and production and endeavour to decouple economic growth from environmental degradation, in accordance with the 10-Year Framework of Programmes on Sustainable Consumption and Production, with developed countries taking the lead.' },
  { code: '8.5', goalNumber: 8, title: 'Full employment and decent work with equal pay', description: 'By 2030, achieve full and productive employment and decent work for all women and men, including for young people and persons with disabilities, and equal pay for work of equal value.' },
  { code: '8.6', goalNumber: 8, title: 'Promote youth employment, education and training', description: 'By 2030, substantially reduce the proportion of youth not in employment, education or training.' },
  { code: '8.7', goalNumber: 8, title: 'End modern slavery, trafficking and child labour', description: 'Take immediate and effective measures to eradicate forced labour, end modern slavery and human trafficking and secure the prohibition and elimination of the worst forms of child labour, including recruitment and use of child soldiers, and by 2025 end child labour in all its forms.' },
  { code: '8.8', goalNumber: 8, title: 'Protect labour rights and promote safe working environments', description: 'Protect labour rights and promote safe and secure working environments for all workers, including migrant workers, in particular women migrants, and those in precarious employment.' },
  { code: '8.9', goalNumber: 8, title: 'Promote beneficial and sustainable tourism', description: 'By 2030, devise and implement policies to promote sustainable tourism that creates jobs and promotes local culture and products.' },
  { code: '8.10', goalNumber: 8, title: 'Universal access to banking, insurance and financial services', description: 'Strengthen the capacity of domestic financial institutions to encourage and expand access to banking, insurance and financial services for all.' },
  { code: '8.A', goalNumber: 8, title: 'Increase aid for trade support', description: 'Increase Aid for Trade support for developing countries, in particular least developed countries, including through the Enhanced Integrated Framework for Trade-related Technical Assistance to Least Developed Countries.' },
  { code: '8.B', goalNumber: 8, title: 'Develop a global youth employment strategy', description: 'By 2030, develop and operationalize a global strategy for youth employment and implement the Global Jobs Pact of the International Labour Organization.' },

  // Goal 9: Industry, Innovation and Infrastructure
  { code: '9.1', goalNumber: 9, title: 'Develop sustainable, resilient and inclusive infrastructures', description: 'Develop quality, reliable, sustainable and resilient infrastructure, including regional and transborder infrastructure, to support economic development and human well-being, with a focus on affordable and equitable access for all.' },
  { code: '9.2', goalNumber: 9, title: 'Promote inclusive and sustainable industrialization', description: "Promote inclusive and sustainable industrialization and, by 2030, significantly raise industry's share of employment and gross domestic product, in line with national circumstances, and double its share in least developed countries." },
  { code: '9.3', goalNumber: 9, title: 'Increase access to financial services and markets', description: 'Increase the access of small-scale industrial and other enterprises, in particular in developing countries, to financial services, including affordable credit, and their integration into value chains and markets.' },
  { code: '9.4', goalNumber: 9, title: 'Upgrade all industries and infrastructures for sustainability', description: 'By 2030, upgrade infrastructure and retrofit industries to make them sustainable, with increased resource-use efficiency and greater adoption of clean and environmentally sound technologies and industrial processes, with all countries taking action in accordance with their respective capabilities.' },
  { code: '9.5', goalNumber: 9, title: 'Enhance research and upgrade industrial technologies', description: 'Enhance scientific research, upgrade the technological capabilities of industrial sectors in all countries, in particular developing countries, including, by 2030, encouraging innovation and substantially increasing the number of research and development workers per 1 million people and public and private research and development spending.' },
  { code: '9.A', goalNumber: 9, title: 'Facilitate sustainable infrastructure development for developing countries', description: 'Facilitate sustainable and resilient infrastructure development in developing countries through enhanced financial, technological and technical support to African countries, least developed countries, landlocked developing countries and small island developing States.' },
  { code: '9.B', goalNumber: 9, title: 'Support domestic technology development and industrial diversification', description: 'Support domestic technology development, research and innovation in developing countries, including by ensuring a conducive policy environment for, inter alia, industrial diversification and value addition to commodities.' },
  { code: '9.C', goalNumber: 9, title: 'Universal access to infomation and communications technology', description: 'Significantly increase access to information and communications technology and strive to provide universal and affordable access to the Internet in least developed countries by 2030.' },

  // Goal 10: Reduced Inequalities
  { code: '10.1', goalNumber: 10, title: 'Reduce income inequalities', description: 'By 2030, progressively achieve and sustain income growth of the bottom 40 per cent of the population at a rate higher than the national average.' },
  { code: '10.2', goalNumber: 10, title: 'Promote universal social, economic and political inclusion', description: 'By 2030, empower and promote the social, economic and political inclusion of all, irrespective of age, sex, disability, race, ethnicity, origin, religion or economic or other status.' },
  { code: '10.3', goalNumber: 10, title: 'Ensure equal opportunities and end discrimination', description: 'Ensure equal opportunity and reduce inequalities of outcome, including by eliminating discriminatory laws, policies and practices and promoting appropriate legislation, policies and action in this regard.' },
  { code: '10.4', goalNumber: 10, title: 'Adopt fiscal and social policies that promote equality', description: 'Adopt policies, especially fiscal, wage and social protection policies, and progressively achieve greater equality.' },
  { code: '10.5', goalNumber: 10, title: 'Improved regulation of global financial markets and institutions', description: 'Improve the regulation and monitoring of global financial markets and institutions and strengthen the implementation of such regulations.' },
  { code: '10.6', goalNumber: 10, title: 'Enhanced representation for developing countries in financial institutions', description: 'Ensure enhanced representation and voice for developing countries in decision-making in global international economic and financial institutions in order to deliver more effective, credible, accountable and legitimate institutions.' },
  { code: '10.7', goalNumber: 10, title: 'Responsible and well-managed migration policies', description: 'Facilitate orderly, safe, regular and responsible migration and mobility of people, including through the implementation of planned and well-managed migration policies.' },
  { code: '10.A', goalNumber: 10, title: 'Special and differential treatment for developing countries', description: 'Implement the principle of special and differential treatment for developing countries, in particular least developed countries, in accordance with World Trade Organization agreements.' },
  { code: '10.B', goalNumber: 10, title: 'Encourage development assistance and investment in least developed countries', description: 'Encourage official development assistance and financial flows, including foreign direct investment, to States where the need is greatest, in particular least developed countries, African countries, small island developing States and landlocked developing countries, in accordance with their national plans and programmes.' },
  { code: '10.C', goalNumber: 10, title: 'Reduce transaction costs for migrant remittances', description: 'By 2030, reduce to less than 3 per cent the transaction costs of migrant remittances and eliminate remittance corridors with costs higher than 5 per cent.' },

  // Goal 11: Sustainable Cities and Communities
  { code: '11.1', goalNumber: 11, title: 'Safe and affordable housing', description: 'By 2030, ensure access for all to adequate, safe and affordable housing and basic services and upgrade slums.' },
  { code: '11.2', goalNumber: 11, title: 'Affordable and sustainable transport systems', description: 'By 2030, provide access to safe, affordable, accessible and sustainable transport systems for all, improving road safety, notably by expanding public transport, with special attention to the needs of those in vulnerable situations, women, children, persons with disabilities and older persons.' },
  { code: '11.3', goalNumber: 11, title: 'Inclusive and sustainable urbanization', description: 'By 2030, enhance inclusive and sustainable urbanization and capacity for participatory, integrated and sustainable human settlement planning and management in all countries.' },
  { code: '11.4', goalNumber: 11, title: "Protect the world's cutural and natural heritage", description: "Strengthen efforts to protect and safeguard the world's cultural and natural heritage." },
  { code: '11.5', goalNumber: 11, title: 'Reduce the adverse effects of natural disasters', description: 'By 2030, significantly reduce the number of deaths and the number of people affected and substantially decrease the direct economic losses relative to global gross domestic product caused by disasters, including water-related disasters, with a focus on protecting the poor and people in vulnerable situations.' },
  { code: '11.6', goalNumber: 11, title: 'Reduce the environmental impact of cities', description: 'By 2030, reduce the adverse per capita environmental impact of cities, including by paying special attention to air quality and municipal and other waste management.' },
  { code: '11.7', goalNumber: 11, title: 'Provide access to safe and inclusive green and public spaces', description: 'By 2030, provide universal access to safe, inclusive and accessible, green and public spaces, in particular for women and children, older persons and persons with disabilities.' },
  { code: '11.A', goalNumber: 11, title: 'Strong national and regional development planning', description: 'Support positive economic, social and environmental links between urban, peri-urban and rural areas by strengthening national and regional development planning.' },
  { code: '11.B', goalNumber: 11, title: 'Implement policies for inclusion, resource efficiency and disaster risk reduction', description: 'By 2030, substantially increase the number of cities and human settlements adopting and implementing integrated policies and plans towards inclusion, resource efficiency, mitigation and adaptation to climate change, resilience to disasters, and develop and implement, in line with the Sendai Framework for Disaster Risk Reduction 2015-2030, holistic disaster risk management at all levels.' },
  { code: '11.C', goalNumber: 11, title: 'Support least developed countries in sustainable and resilient building', description: 'Support least developed countries, including through financial and technical assistance, in building sustainable and resilient buildings utilizing local materials.' },

  // Goal 12: Responsible Consumption and Production
  { code: '12.1', goalNumber: 12, title: 'Implement the 10-year sustainable consumption and production framework', description: 'Implement the 10-Year Framework of Programmes on Sustainable Consumption and Production Patterns, all countries taking action, with developed countries taking the lead, taking into account the development and capabilities of developing countries.' },
  { code: '12.2', goalNumber: 12, title: 'Sustainable management and use of natural resources', description: 'By 2030, achieve the sustainable management and efficient use of natural resources.' },
  { code: '12.3', goalNumber: 12, title: 'Halve global per capita food waste', description: 'By 2030, halve per capita global food waste at the retail and consumer levels and reduce food losses along production and supply chains, including post-harvest losses.' },
  { code: '12.4', goalNumber: 12, title: 'Responsible management of chemicals and waste', description: 'By 2030, achieve the environmentally sound management of chemicals and all wastes throughout their life cycle, in accordance with agreed international frameworks, and significantly reduce their release to air, water and soil in order to minimize their adverse impacts on human health and the environment.' },
  { code: '12.5', goalNumber: 12, title: 'Substantially reduce waste generation', description: 'By 2030, substantially reduce waste generation through prevention, reduction, recycling and reuse.' },
  { code: '12.6', goalNumber: 12, title: 'Encourage companies to adopt sustainable practices and sustainability reporting', description: 'Encourage companies, especially large and transnational companies, to adopt sustainable practices and to integrate sustainability information into their reporting cycle.' },
  { code: '12.7', goalNumber: 12, title: 'Promote sustainable public procurement practices', description: 'Promote public procurement practices that are sustainable, in accordance with national policies and priorities.' },
  { code: '12.8', goalNumber: 12, title: 'Promote universal understanding of sustainable lifestyles', description: 'By 2030, ensure that people everywhere have the relevant information and awareness for sustainable development and lifestyles in harmony with nature.' },
  { code: '12.A', goalNumber: 12, title: "Support developing countries' scientific and technological capacity for sustainable consumption and production", description: 'Support developing countries to strengthen their scientific and technological capacity to move towards more sustainable patterns of consumption and production.' },
  { code: '12.B', goalNumber: 12, title: 'Develop and implement tools to monitor sustainable tourism', description: 'Develop and implement tools to monitor sustainable development impacts for sustainable tourism that creates jobs and promotes local culture and products.' },
  { code: '12.C', goalNumber: 12, title: 'Remove market distortions that encourage wasteful consumption', description: 'Rationalize inefficient fossil-fuel subsidies that encourage wasteful consumption by removing market distortions, in accordance with national circumstances, including by restructuring taxation and phasing out those harmful subsidies, where they exist, to reflect their environmental impacts, taking fully into account the specific needs and conditions of developing countries and minimizing the possible adverse impacts on their development in a manner that protects the poor and the affected communities.' },

  // Goal 13: Climate Action
  { code: '13.1', goalNumber: 13, title: 'Strengthen resilience and adaptive capacity to climate related disasters', description: 'Strengthen resilience and adaptive capacity to climate-related hazards and natural disasters in all countries.' },
  { code: '13.2', goalNumber: 13, title: 'Integrate climate change measures into policies and planning', description: 'Integrate climate change measures into national policies, strategies and planning.' },
  { code: '13.3', goalNumber: 13, title: 'Build knowledge and capacity to meet climate change', description: 'Improve education, awareness-raising and human and institutional capacity on climate change mitigation, adaptation, impact reduction and early warning.' },
  { code: '13.A', goalNumber: 13, title: 'Implement the UN framework convention on climate change', description: 'Implement the commitment undertaken by developed-country parties to the United Nations Framework Convention on Climate Change to a goal of mobilizing jointly $100 billion annually by 2020 from all sources to address the needs of developing countries in the context of meaningful mitigation actions and transparency on implementation and fully operationalize the Green Climate Fund through its capitalization as soon as possible.' },
  { code: '13.B', goalNumber: 13, title: 'Promote mechanisms to raise capacity for planning and management', description: 'Promote mechanisms for raising capacity for effective climate change-related planning and management in least developed countries and small island developing States, including focusing on women, youth and local and marginalized communities.' },

  // Goal 14: Life Below Water
  { code: '14.1', goalNumber: 14, title: 'Reduce marine pollution', description: 'By 2030, prevent and significantly reduce marine pollution of all kinds, in particular from land-based activities, including marine debris and nutrient pollution.' },
  { code: '14.2', goalNumber: 14, title: 'Protect and restore ecosystems', description: 'By 2030, sustainably manage and protect marine and coastal ecosystems to avoid significant adverse impacts, including by strengthening their resilience, and take action for their restoration in order to achieve healthy and productive oceans.' },
  { code: '14.3', goalNumber: 14, title: 'Reduce ocean acidification', description: 'Minimize and address the impacts of ocean acidification, including through enhanced scientific cooperation at all levels.' },
  { code: '14.4', goalNumber: 14, title: 'Sustainable Fishing', description: 'By 2030, effectively regulate harvesting and end overfishing, illegal, unreported and unregulated fishing and destructive fishing practices and implement science-based management plans, in order to restore fish stocks in the shortest time feasible, at least to levels that can produce maximum sustainable yield as determined by their biological characteristics.' },
  { code: '14.5', goalNumber: 14, title: 'Conserve coastal and marine areas', description: 'By 2030, conserve at least 10 per cent of coastal and marine areas, consistent with national and international law and based on the best available scientific information.' },
  { code: '14.6', goalNumber: 14, title: 'End subsidies contributing to overfishing', description: 'By 2030, prohibit certain forms of fisheries subsidies which contribute to overcapacity and overfishing, eliminate subsidies that contribute to illegal, unreported and unregulated fishing and refrain from introducing new such subsidies, recognizing that appropriate and effective special and differential treatment for developing and least developed countries should be an integral part of the World Trade Organization fisheries subsidies negotiation.' },
  { code: '14.7', goalNumber: 14, title: 'Increase the economic benefits from sustainable use of marine resources', description: 'By 2030, increase the economic benefits to small island developing States and least developed countries from the sustainable use of marine resources, including through sustainable management of fisheries, aquaculture and tourism.' },
  { code: '14.A', goalNumber: 14, title: 'Increase scientific knowledge, research and technology for ocean health', description: 'Increase scientific knowledge, develop research capacity and transfer marine technology, taking into account the Intergovernmental Oceanographic Commission Criteria and Guidelines on the Transfer of Marine Technology, in order to improve ocean health and to enhance the contribution of marine biodiversity to the development of developing countries, in particular small island developing States and least developed countries.' },
  { code: '14.B', goalNumber: 14, title: 'Support small scale fishers', description: 'Provide access for small-scale artisanal fishers to marine resources and markets.' },
  { code: '14.C', goalNumber: 14, title: 'Implement and enforce international sea law', description: 'Enhance the conservation and sustainable use of oceans and their resources by implementing international law as reflected in the United Nations Convention on the Law of the Sea, which provides the legal framework for the conservation and sustainable use of oceans and their resources, as recalled in paragraph 158 of "The future we want".' },

  // Goal 15: Life On Land
  { code: '15.1', goalNumber: 15, title: 'Conserve and restore terrestrial and freshwater ecosystems', description: 'By 2030, prevent and significantly reduce marine pollution of all kinds, in particular from land-based activities, including marine debris and nutrient pollution.' },
  { code: '15.2', goalNumber: 15, title: 'End deforestation and restore degraded forests', description: 'By 2030, promote the implementation of sustainable management of all types of forests, halt deforestation, restore degraded forests and substantially increase afforestation and reforestation globally.' },
  { code: '15.3', goalNumber: 15, title: 'End desertification and restore degraded land', description: 'By 2030, combat desertification, restore degraded land and soil, including land affected by desertification, drought and floods, and strive to achieve a land degradation-neutral world.' },
  { code: '15.4', goalNumber: 15, title: 'Ensure conservation of mountain ecosystems', description: 'By 2030, ensure the conservation of mountain ecosystems, including their biodiversity, in order to enhance their capacity to provide benefits that are essential for sustainable development.' },
  { code: '15.5', goalNumber: 15, title: 'Protect biodiversity and natural habitats', description: 'Take urgent and significant action to reduce the degradation of natural habitats, halt the loss of biodiversity and, by 2030, protect and prevent the extinction of threatened species.' },
  { code: '15.6', goalNumber: 15, title: 'Promote access to genetic resources and fair sharing of the benefits', description: 'Promote fair and equitable sharing of the benefits arising from the utilization of genetic resources and promote appropriate access to such resources, as internationally agreed.' },
  { code: '15.7', goalNumber: 15, title: 'Eliminate poaching and trafficking of protected species', description: 'Take urgent action to end poaching and trafficking of protected species of flora and fauna and address both demand and supply of illegal wildlife products.' },
  { code: '15.8', goalNumber: 15, title: 'Prevent invasive alien species on land and water ecosystems', description: 'By 2030, introduce measures to prevent the introduction and significantly reduce the impact of invasive alien species on land and water ecosystems and control or eradicate the priority species.' },
  { code: '15.9', goalNumber: 15, title: 'Intergrate ecosystem and biodiversity in government planning', description: 'By 2030, integrate ecosystem and biodiversity values into national and local planning, development processes, poverty reduction strategies and accounts.' },
  { code: '15.A', goalNumber: 15, title: 'Increase financial resources to conserve and sustainably use ecosystem and biodiversity', description: 'Mobilize and significantly increase financial resources from all sources to conserve and sustainably use biodiversity and ecosystems.' },
  { code: '15.B', goalNumber: 15, title: 'Finance and incentivize sustainable forest management', description: 'Mobilize significant resources from all sources and at all levels to finance sustainable forest management and provide adequate incentives to developing countries to advance such management, including for conservation and reforestation.' },
  { code: '15.C', goalNumber: 15, title: 'Combat global poaching and trafficking', description: 'Enhance global support for efforts to combat poaching and trafficking of protected species, including by increasing the capacity of local communities to pursue sustainable livelihood opportunities.' },

  // Goal 16: Peace, Justice and Strong Institutions
  { code: '16.1', goalNumber: 16, title: 'Reduce violence everywhere', description: 'Significantly reduce all forms of violence and related death rates everywhere.' },
  { code: '16.2', goalNumber: 16, title: 'Protect children from abuse, exploitation, trafficking and violence', description: 'End abuse, exploitation, trafficking and all forms of violence against and torture of children.' },
  { code: '16.3', goalNumber: 16, title: 'Promote the rule of law and ensure equal access to justice', description: 'Promote the rule of law at the national and international levels and ensure equal access to justice for all.' },
  { code: '16.4', goalNumber: 16, title: 'Combat organized crime and illicit financial and arms flows', description: 'By 2030, significantly reduce illicit financial and arms flows, strengthen the recovery and return of stolen assets and combat all forms of organized crime.' },
  { code: '16.5', goalNumber: 16, title: 'Substantially reduce corruption and bribery', description: 'Substantially reduce corruption and bribery in all their forms.' },
  { code: '16.6', goalNumber: 16, title: 'Develop effective, accountable and transparent institutions', description: 'Develop effective, accountable and transparent institutions at all levels.' },
  { code: '16.7', goalNumber: 16, title: 'Ensure responsive, inclusive and representative decision-making', description: 'Ensure responsive, inclusive, participatory and representative decision-making at all levels.' },
  { code: '16.8', goalNumber: 16, title: 'Strengthen the participation in global governance', description: 'Broaden and strengthen the participation of developing countries in the institutions of global governance.' },
  { code: '16.9', goalNumber: 16, title: 'Provide universal legal identity', description: 'By 2030, provide legal identity for all, including birth registration.' },
  { code: '16.10', goalNumber: 16, title: 'Ensure public access to infomation and protect fundamental freedoms', description: 'Ensure public access to information and protect fundamental freedoms, in accordance with national legislation and international agreements.' },
  { code: '16.A', goalNumber: 16, title: 'Strengthen national institutions to prevent violence and combat terrorism and crime', description: 'Strengthen relevant national institutions, including through international cooperation, for building capacity at all levels, in particular in developing countries, to prevent violence and combat terrorism and crime.' },
  { code: '16.B', goalNumber: 16, title: 'Promote and enforce non-discriminatory laws and policies', description: 'Promote and enforce non-discriminatory laws and policies for sustainable development.' },

  // Goal 17: Partnerships for the Goals
  { code: '17.1', goalNumber: 17, title: 'Mobilize resources to improve domestic revenue collection', description: 'Strengthen domestic resource mobilization, including through international support to developing countries, to improve domestic capacity for tax and other revenue collection.' },
  { code: '17.2', goalNumber: 17, title: 'Implement all development assistance commitments', description: 'Developed countries to implement fully their official development assistance commitments, including the commitment by many developed countries to achieve the target of 0.7 per cent of gross national income for official development assistance (ODA/GNI) to developing countries and 0.15 to 0.20 per cent of ODA/GNI to least developed countries; ODA providers are encouraged to consider setting a target to provide at least 0.20 per cent of ODA/GNI to least developed countries.' },
  { code: '17.3', goalNumber: 17, title: 'Mobilize financial resources for devleoping countries', description: 'Mobilize additional financial resources for developing countries from multiple sources.' },
  { code: '17.4', goalNumber: 17, title: 'Assist developing countries in attaining debt sustainability', description: 'Assist developing countries in attaining long-term debt sustainability through coordinated policies aimed at fostering debt financing, debt relief and debt restructuring, as appropriate, and address the external debt of highly indebted poor countries to reduce debt distress.' },
  { code: '17.5', goalNumber: 17, title: 'Invest in least developed countries', description: 'Adopt and implement investment promotion regimes for least developed countries.' },
  { code: '17.6', goalNumber: 17, title: 'Knowledge sharing and cooperation for access to science, technology and innovation', description: 'Enhance North-South, South-South and triangular regional and international cooperation on and access to science, technology and innovation and enhance knowledge sharing on mutually agreed terms, including through improved coordination among existing mechanisms, in particular at the United Nations level, and through a global technology facilitation mechanism.' },
  { code: '17.7', goalNumber: 17, title: 'Promote sustainable technologies to developing countries', description: 'Promote the development, transfer, dissemination and diffusion of environmentally sound technologies to developing countries on favourable terms, including on concessional and preferential terms, as mutually agreed.' },
  { code: '17.8', goalNumber: 17, title: 'Strengthen the science, technology and innovation capacity for least developed countries', description: 'Fully operationalize the technology bank and science, technology and innovation capacity-building mechanism for least developed countries by 2017 and enhance the use of enabling technology, in particular information and communications technology.' },
  { code: '17.9', goalNumber: 17, title: 'Enhance SDG capacity in developing countries', description: 'Enhance international support for implementing effective and targeted capacity-building in developing countries to support national plans to implement all the Sustainable Development Goals, including through North-South, South-South and triangular cooperation.' },
  { code: '17.10', goalNumber: 17, title: 'Promote a universal trading system under the WTO', description: 'Promote a universal, rules-based, open, non-discriminatory and equitable multilateral trading system under the World Trade Organization, including through the conclusion of negotiations under its Doha Development Agenda.' },
  { code: '17.11', goalNumber: 17, title: 'Increase the exports of developing countries', description: "Significantly increase the exports of developing countries, in particular with a view to doubling the least developed countries' share of global exports by 2020." },
  { code: '17.12', goalNumber: 17, title: 'Remove trade barriers for least developed countries', description: 'Realize timely implementation of duty-free and quota-free market access on a lasting basis for all least developed countries, consistent with World Trade Organization decisions, including by ensuring that preferential rules of origin applicable to imports from least developed countries are transparent and simple, and contribute to facilitating market access.' },
  { code: '17.13', goalNumber: 17, title: 'Enhance global macroeconomic stability', description: 'Enhance global macroeconomic stability, including through policy coordination and policy coherence.' },
  { code: '17.14', goalNumber: 17, title: 'Enhance policy coherence for sustainable development', description: 'Enhance policy coherence for sustainable development.' },
  { code: '17.15', goalNumber: 17, title: 'Respect national leadership to implement policies for the sustainable development goals', description: "Respect each country's policy space and leadership to establish and implement policies for poverty eradication and sustainable development." },
  { code: '17.16', goalNumber: 17, title: 'Enhance the global partnership for sustainable development', description: "Respect each country's policy space and leadership to establish and implement policies for poverty eradication and sustainable development." },
  { code: '17.17', goalNumber: 17, title: 'Encourage effective partnerships', description: 'Encourage and promote effective public, public-private and civil society partnerships, building on the experience and resourcing strategies of partnerships.' },
  { code: '17.18', goalNumber: 17, title: 'Enhance availability of reliable data', description: 'By 2030, enhance capacity-building support to developing countries, including for least developed countries and small island developing States, to increase significantly the availability of high-quality, timely and reliable data disaggregated by income, gender, age, race, ethnicity, migratory status, disability, geographic location and other characteristics relevant in national contexts.' },
  { code: '17.19', goalNumber: 17, title: 'Further develop measurments of progress', description: 'By 2030, build on existing initiatives to develop measurements of progress on sustainable development that complement gross domestic product, and support statistical capacity-building in developing countries.' },
]
