/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    researchers: Researcher;
    institutions: Institution;
    'research-groups': ResearchGroup;
    'sdg-goals': SdgGoal;
    'sdg-targets': SdgTarget;
    jobs: Job;
    'pricing-tiers': PricingTier;
    posts: Post;
    'post-categories': PostCategory;
    'team-members': TeamMember;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    researchers: ResearchersSelect<false> | ResearchersSelect<true>;
    institutions: InstitutionsSelect<false> | InstitutionsSelect<true>;
    'research-groups': ResearchGroupsSelect<false> | ResearchGroupsSelect<true>;
    'sdg-goals': SdgGoalsSelect<false> | SdgGoalsSelect<true>;
    'sdg-targets': SdgTargetsSelect<false> | SdgTargetsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'pricing-tiers': PricingTiersSelect<false> | PricingTiersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'post-categories': PostCategoriesSelect<false> | PostCategoriesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'en' | 'en'[];
  globals: {};
  globalsSelect: {};
  locale: 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'researcher' | 'employer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "researchers".
 */
export interface Researcher {
  id: number;
  /**
   * The account that owns/can edit this profile (self-registration flow)
   */
  user?: (number | null) | User;
  /**
   * e.g. "ms-xiaoxiao-qian" — combined with institution slug for the profile URL
   */
  slug: string;
  /**
   * "Ms", "Dr", "Prof", etc.
   */
  title?: string | null;
  firstNames?: string | null;
  lastName?: string | null;
  /**
   * Post-nominal letters, e.g. "PhD FHEA" — free text in the source, quality varies
   */
  abbreviations?: string | null;
  /**
   * Display name used across the directory and as the admin title
   */
  fullName: string;
  /**
   * e.g. "Educational Scientist"
   */
  position?: string | null;
  /**
   * ACF repeater "additional_job_title" — extra roles beyond the primary position
   */
  additionalJobTitles?:
    | {
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  institution?: (number | null) | Institution;
  /**
   * Free-text current employer, used when it differs from the linked institution
   */
  currentPlaceOfWork?: string | null;
  photo?: (number | null) | Media;
  /**
   * Original image URL from the WordPress export — filled in by the data migration, left for a later image-import pass to download and attach as the real "photo" upload. Safe to ignore once photo is set.
   */
  photoSourceUrl?: string | null;
  /**
   * ISO 3166-1 alpha-2, e.g. "CN" — feeds the country filter on the directory
   */
  countryCode?: string | null;
  /**
   * ISO alpha-2 where available — source data has some non-conforming legacy values
   */
  additionalCountry1?: string | null;
  additionalCountry2?: string | null;
  languages?: string[] | null;
  researchFocus?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Which UN SDG targets this researcher's work maps to — feeds the goal filter and badges
   */
  sdgTargets?: (number | SdgTarget)[] | null;
  projects?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  researchGroupName?: string | null;
  researchGroupUrl?: string | null;
  additionalResearchGroups?:
    | {
        name?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Free-text list of publications/citations
   */
  citations?: string | null;
  phdsSupervised?: number | null;
  phdSupervisorName?: string | null;
  /**
   * Free text in the source, not a real date — mostly a bare year ("2024") or the literal status "phd-completed"
   */
  phdCompletionDate?: string | null;
  professionalOrganisation?: string | null;
  additionalOrganisations?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Facebook
   */
  facebook?: string | null;
  /**
   * Twitter/X
   */
  twitter?: string | null;
  /**
   * LinkedIn
   */
  linkedin?: string | null;
  /**
   * Google Scholar
   */
  googleScholar?: string | null;
  /**
   * ResearchGate
   */
  researchGate?: string | null;
  /**
   * Mendeley
   */
  mendeley?: string | null;
  /**
   * Wikipedia
   */
  wikipedia?: string | null;
  /**
   * Bluesky
   */
  bluesky?: string | null;
  /**
   * Mastodon
   */
  mastodon?: string | null;
  /**
   * Threads
   */
  threads?: string | null;
  /**
   * ACF "other_social_1" – "other_social_3"
   */
  otherSocialLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * YouTube/Vimeo profile video
   */
  videoUrl?: string | null;
  /**
   * ACF Google Map field, raw value — populated on only 2 of ~700 profiles in the source data and both values look like attachment/post IDs rather than coordinates, so this is kept as plain text rather than a geo field until that's understood. Safe to ignore for most profiles.
   */
  location?: string | null;
  /**
   * "Trailblazer" spotlight flag — clean Yes/No field in the source (38 Yes / 681 No)
   */
  trailblazer?: boolean | null;
  /**
   * Unpublish instead of delete to preserve edit history
   */
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutions".
 */
export interface Institution {
  id: number;
  name: string;
  /**
   * Used in researcher profile URLs, e.g. /humboldt-universitity-zu-berlin/ms-xiaoxiao-qian/
   */
  slug: string;
  motto?: string | null;
  logo?: (number | null) | Media;
  /**
   * Original logo URL from WordPress — see Researchers.photoSourceUrl
   */
  logoSourceUrl?: string | null;
  /**
   * City/country as free text — source is a plain ACF text field, not a map
   */
  location?: string | null;
  /**
   * ACF "url" — the institution's own homepage
   */
  websiteUrl?: string | null;
  /**
   * Link to this institution's jobs/listings on the source site
   */
  listingsUrl?: string | null;
  rootUrl?: string | null;
  awards?: string | null;
  rankings?: string | null;
  /**
   * ACF "key_facts"
   */
  keyFacts?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * ACF "institution_main_text" — the institution's profile-page body copy
   */
  mainText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Legacy WP shortcode embedded on the institution page ("search_shortcode") — kept for reference only, has no equivalent in the headless frontend
   */
  searchShortcode?: string | null;
  /**
   * Currency used when this institution posts paid job listings, e.g. "GBP"
   */
  jobListingCurrency?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Seed data — full UN target list. See src/seed/sdgs.ts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sdg-targets".
 */
export interface SdgTarget {
  id: number;
  /**
   * e.g. "4.1" or "4.A" — targets run past the numbered ones into lettered sub-targets
   */
  code: string;
  goal: number | SdgGoal;
  title: string;
  /**
   * Full UN target text
   */
  description: string;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Seed data — the 17 UN Sustainable Development Goals. See src/seed/sdgs.ts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sdg-goals".
 */
export interface SdgGoal {
  id: number;
  /**
   * 1 through 17
   */
  number: number;
  /**
   * e.g. "goal-04" — matches the country/goal filter values on the live site
   */
  code: string;
  title: string;
  /**
   * Official SDG color, used for the goal-dot badges
   */
  colorHex?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-groups".
 */
export interface ResearchGroup {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * ACF "research_group_focus" — the group's mission/overview copy
   */
  focus?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  researchers?: (number | Researcher)[] | null;
  /**
   * ISO 3166-1 alpha-2, e.g. "AU"
   */
  mainCountry?: string | null;
  /**
   * ACF "goals" repeater on the group
   */
  sdgGoals?: (number | SdgGoal)[] | null;
  /**
   * ACF "current_research" repeater
   */
  currentResearch?:
    | {
        title?: string | null;
        description?: string | null;
        sdgGoals?: (number | SdgGoal)[] | null;
        videos?:
          | {
              title?: string | null;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * ACF "research_group_video" — a single overview video for the group
   */
  video?: string | null;
  universityLogo?: (number | null) | Media;
  /**
   * Original URL from WordPress — see Researchers.photoSourceUrl
   */
  universityLogoSourceUrl?: string | null;
  groupPhoto?: (number | null) | Media;
  /**
   * Original URL from WordPress — see Researchers.photoSourceUrl
   */
  groupPhotoSourceUrl?: string | null;
  /**
   * ACF Google Map field, raw value — rarely populated, kept as plain text (see Researchers.location)
   */
  groupMap?: string | null;
  facebook?: string | null;
  twitter?: string | null;
  linkedin?: string | null;
  wikipedia?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  employer?: (number | null) | User;
  title: string;
  slug: string;
  companyName: string;
  /**
   * ACF "employer_type" — almost always "Universities" in the source data
   */
  employerType?: string | null;
  /**
   * Link to the employer's institution/profile page
   */
  employerPage?: string | null;
  location?: string | null;
  isRemote?: boolean | null;
  jobTypes?:
    ('fixed_term' | 'freelance' | 'full_time' | 'internship' | 'part_time' | 'permanent' | 'temporary')[] | null;
  /**
   * ACF "academic_staff__faculty_roles"
   */
  academicStaffFacultyRoles?:
    | (
        | 'research_assistant'
        | 'research_associate_fellow'
        | 'postdoc'
        | 'lecturer'
        | 'senior_lecturer'
        | 'associate_assistant_professor'
        | 'professor'
        | 'head_of_school_dept_research_centre'
        | 'engineer'
        | 'phd_studentship'
      )[]
    | null;
  /**
   * Academic subject area(s) — ACF "sector"
   */
  sector?:
    | (
        | 'agriculture_and_veterinary_sciences'
        | 'art_and_design'
        | 'arts_and_humanities'
        | 'biology'
        | 'business_and_management'
        | 'chemistry'
        | 'clinical'
        | 'computer_science'
        | 'economics_and_finance'
        | 'education'
        | 'engineering'
        | 'food_sciences'
        | 'geography_and_environmental_sciences'
        | 'health_and_medical'
        | 'law'
        | 'marine_sciences'
        | 'materials_sciences'
        | 'mathematics'
        | 'physics'
        | 'social_sciences'
        | 'sports_sciences'
        | 'statistics'
      )[]
    | null;
  /**
   * From the job_listing_category taxonomy, which on this site is used for SDG goal tagging ("Goal 01 No Poverty", etc.), not a generic job category
   */
  sdgGoals?: (number | SdgGoal)[] | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  applicationUrl?: string | null;
  applicationEmail?: string | null;
  /**
   * Employer's own internal reference/req ID for the vacancy
   */
  jobReference?: string | null;
  /**
   * WP Job Manager "_job_salary" — free text, e.g. "39,105 - 46,485"
   */
  salaryText?: string | null;
  /**
   * e.g. "UKP", "AUD", "USD" — legacy codes, not always ISO 4217
   */
  salaryCurrency?: string | null;
  /**
   * e.g. "YEAR"
   */
  salaryUnit?: string | null;
  /**
   * WP Job Manager "_job_expires"
   */
  expiresAt?: string | null;
  sdgTargets?: (number | SdgTarget)[] | null;
  priceTier?: (number | null) | PricingTier;
  paymentStatus?: ('unpaid' | 'pending' | 'paid' | 'refunded') | null;
  stripePaymentIntentId?: string | null;
  /**
   * Flip true once payment clears — see plugins/stripe.ts webhook handler
   */
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-tiers".
 */
export interface PricingTier {
  id: number;
  /**
   * e.g. "Standard listing", "Featured listing"
   */
  name: string;
  priceCents: number;
  currency?: string | null;
  durationDays?: number | null;
  /**
   * Price ID from the Stripe dashboard — see plugins/stripe.ts
   */
  stripePriceId?: string | null;
  stripeID?: string | null;
  skipSync?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  categories?: (number | PostCategory)[] | null;
  author?: (number | null) | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories".
 */
export interface PostCategory {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  fullName: string;
  role: string;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo?: (number | null) | Media;
  socialLinks?:
    | {
        platform?: ('twitter' | 'linkedin' | 'facebook' | 'youtube' | 'mastodon' | 'bluesky') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  slug: string;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'researchers';
        value: number | Researcher;
      } | null)
    | ({
        relationTo: 'institutions';
        value: number | Institution;
      } | null)
    | ({
        relationTo: 'research-groups';
        value: number | ResearchGroup;
      } | null)
    | ({
        relationTo: 'sdg-goals';
        value: number | SdgGoal;
      } | null)
    | ({
        relationTo: 'sdg-targets';
        value: number | SdgTarget;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'pricing-tiers';
        value: number | PricingTier;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'post-categories';
        value: number | PostCategory;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "researchers_select".
 */
export interface ResearchersSelect<T extends boolean = true> {
  user?: T;
  slug?: T;
  title?: T;
  firstNames?: T;
  lastName?: T;
  abbreviations?: T;
  fullName?: T;
  position?: T;
  additionalJobTitles?:
    | T
    | {
        title?: T;
        id?: T;
      };
  institution?: T;
  currentPlaceOfWork?: T;
  photo?: T;
  photoSourceUrl?: T;
  countryCode?: T;
  additionalCountry1?: T;
  additionalCountry2?: T;
  languages?: T;
  researchFocus?: T;
  sdgTargets?: T;
  projects?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  researchGroupName?: T;
  researchGroupUrl?: T;
  additionalResearchGroups?:
    | T
    | {
        name?: T;
        url?: T;
        id?: T;
      };
  citations?: T;
  phdsSupervised?: T;
  phdSupervisorName?: T;
  phdCompletionDate?: T;
  professionalOrganisation?: T;
  additionalOrganisations?:
    | T
    | {
        name?: T;
        id?: T;
      };
  facebook?: T;
  twitter?: T;
  linkedin?: T;
  googleScholar?: T;
  researchGate?: T;
  mendeley?: T;
  wikipedia?: T;
  bluesky?: T;
  mastodon?: T;
  threads?: T;
  otherSocialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  videoUrl?: T;
  location?: T;
  trailblazer?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutions_select".
 */
export interface InstitutionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  motto?: T;
  logo?: T;
  logoSourceUrl?: T;
  location?: T;
  websiteUrl?: T;
  listingsUrl?: T;
  rootUrl?: T;
  awards?: T;
  rankings?: T;
  keyFacts?: T;
  mainText?: T;
  searchShortcode?: T;
  jobListingCurrency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-groups_select".
 */
export interface ResearchGroupsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  focus?: T;
  researchers?: T;
  mainCountry?: T;
  sdgGoals?: T;
  currentResearch?:
    | T
    | {
        title?: T;
        description?: T;
        sdgGoals?: T;
        videos?:
          | T
          | {
              title?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  video?: T;
  universityLogo?: T;
  universityLogoSourceUrl?: T;
  groupPhoto?: T;
  groupPhotoSourceUrl?: T;
  groupMap?: T;
  facebook?: T;
  twitter?: T;
  linkedin?: T;
  wikipedia?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sdg-goals_select".
 */
export interface SdgGoalsSelect<T extends boolean = true> {
  number?: T;
  code?: T;
  title?: T;
  colorHex?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sdg-targets_select".
 */
export interface SdgTargetsSelect<T extends boolean = true> {
  code?: T;
  goal?: T;
  title?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  employer?: T;
  title?: T;
  slug?: T;
  companyName?: T;
  employerType?: T;
  employerPage?: T;
  location?: T;
  isRemote?: T;
  jobTypes?: T;
  academicStaffFacultyRoles?: T;
  sector?: T;
  sdgGoals?: T;
  description?: T;
  applicationUrl?: T;
  applicationEmail?: T;
  jobReference?: T;
  salaryText?: T;
  salaryCurrency?: T;
  salaryUnit?: T;
  expiresAt?: T;
  sdgTargets?: T;
  priceTier?: T;
  paymentStatus?: T;
  stripePaymentIntentId?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-tiers_select".
 */
export interface PricingTiersSelect<T extends boolean = true> {
  name?: T;
  priceCents?: T;
  currency?: T;
  durationDays?: T;
  stripePriceId?: T;
  stripeID?: T;
  skipSync?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  categories?: T;
  author?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories_select".
 */
export interface PostCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  bio?: T;
  photo?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}